version: 1.0
provider:
  name: openfaas
  gateway: https://dfd-openfaas.iits.tech
functions:
  faas-deployer:
    lang: dockerfile
    handler: ./faas-deployer
    image: iits/dfd-faas-deployer:latest
  slack-middleware:
    lang: node12
    handler: ./slack-middleware
    image: iits/dfd-slack-middleware:latest