version: 1.0
provider:
  name: openfaas
  gateway: https://dfd-openfaas.iits.tech
functions:
  faas-deployer:
    lang: dockerfile
    handler: ./faas-deployer
    image:  ghcr.io/iits-consulting/faas-deployer:latest
    secrets:
      - ghcr-token

